<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>AutoOS.App</RootNamespace>
    <AssemblyName>AutoOS</AssemblyName>
    <ApplicationIcon>Assets\AppIcon.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Version>1.4.7.1</Version>
    <TargetFramework>$(WindowsTargetFramework)</TargetFramework>
    <TargetPlatformMinVersion>$(MinimalWindowsVersion)</TargetPlatformMinVersion>

    <Platforms>x86;x64;ARM64</Platforms>
    <RuntimeIdentifiers>win-x86;win-x64;win-arm64</RuntimeIdentifiers>
    <EnableMsixTooling>true</EnableMsixTooling>
    <OutputType>WinExe</OutputType>

    <Nullable>Enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <TrimMode>full</TrimMode>
    <CsWinRTAotWarningLevel>2</CsWinRTAotWarningLevel>

    <PublishAot>False</PublishAot>
    <PublishDir>bin\$(Configuration)\$(TargetFramework)\$(RuntimeIdentifier)\publish\</PublishDir>
    <PublishProfile>Properties\PublishProfiles\win-$(Platform).pubxml</PublishProfile>
    <PublishReadyToRun Condition="'$(Configuration)' == 'Debug'">False</PublishReadyToRun>
    <PublishReadyToRun Condition="'$(Configuration)' != 'Debug'">True</PublishReadyToRun>
    <PublishReadyToRunComposite Condition="'$(Configuration)' != 'Debug'">True</PublishReadyToRunComposite>
    <PublishTrimmed Condition="'$(Configuration)' == 'Debug'">False</PublishTrimmed>
    <PublishTrimmed Condition="'$(Configuration)' != 'Debug'">True</PublishTrimmed>
    <SelfContained Condition="'$(Configuration)' != 'Debug'">True</SelfContained>
    <WindowsAppSDKSelfContained>true</WindowsAppSDKSelfContained>
    <WindowsPackageType>MSIX</WindowsPackageType>
    <AppxBundle>Never</AppxBundle>
    <AppxSymbolPackageEnabled>False</AppxSymbolPackageEnabled>
    <AppxPackageSigningEnabled>True</AppxPackageSigningEnabled>
    <PackageCertificateKeyFile>C:\Users\AutoOS\Desktop\AutoOS\AutoOS_TemporaryKey.pfx</PackageCertificateKeyFile>
    <GenerateAppInstallerFile>False</GenerateAppInstallerFile>
    <AppxPackageSigningTimestampDigestAlgorithm>SHA256</AppxPackageSigningTimestampDigestAlgorithm>
    <AppxAutoIncrementPackageRevision>False</AppxAutoIncrementPackageRevision>
    <GenerateTestArtifacts>False</GenerateTestArtifacts>
    <HoursBetweenUpdateChecks>0</HoursBetweenUpdateChecks>
  </PropertyGroup>

  <ItemGroup>
    <Manifest Include="$(ApplicationManifest)" />
  </ItemGroup>

  <ItemGroup>
    <TrimmerRootAssembly Include="Syncfusion.Calendar.WinUI" />
    <TrimmerRootAssembly Include="Syncfusion.Chart.WinUI" />
    <TrimmerRootAssembly Include="Syncfusion.Core.WinUI" />
    <TrimmerRootAssembly Include="Syncfusion.Data.WinUI" />
    <TrimmerRootAssembly Include="Syncfusion.Editors.WinUI" />
    <TrimmerRootAssembly Include="Syncfusion.Grid.WinUI" />
    <TrimmerRootAssembly Include="Syncfusion.Licensing" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Labs.WinUI.Controls.DataTable" />
    <PackageReference Include="CommunityToolkit.Labs.WinUI.Controls.MarkdownTextBlock" />
    <PackageReference Include="CommunityToolkit.Mvvm" />
    <PackageReference Include="CommunityToolkit.WinUI.Controls.HeaderedControls" />
    <PackageReference Include="CommunityToolkit.WinUI.Controls.Primitives" />
    <PackageReference Include="CommunityToolkit.WinUI.Controls.TabbedCommandBar" />
    <PackageReference Include="CommunityToolkit.WinUI.Converters" />
    <PackageReference Include="DevWinUI" />
    <PackageReference Include="Sep" />
    <PackageReference Include="Microsoft.Windows.CsWin32" />
    <PackageReference Include="Microsoft.Windows.CsWinRT" />
    <PackageReference Include="Microsoft.Windows.SDK.BuildTools" />
    <PackageReference Include="Microsoft.WindowsAppSDK" />
    <PackageReference Include="Microsoft.Diagnostics.Tracing.TraceEvent" />
    <PackageReference Include="Newtonsoft.Json" />
    <PackageReference Include="nucs.JsonSettings" />
    <PackageReference Include="nucs.JsonSettings.AutoSaveGenerator" />
    <PackageReference Include="System.ServiceProcess.ServiceController" />
    <PackageReference Include="Syncfusion.Chart.WinUI" />
    <PackageReference Include="Syncfusion.Grid.WinUI" />
    <PackageReference Include="ValveKeyValue" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AutoOS.Core\AutoOS.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\..\artifacts\$(Configuration)\x64\AutoOS.App.Sound\AutoOS.Sound.exe" Link="AutoOS.Sound.exe" Condition="Exists('..\..\artifacts\$(Configuration)\x64\AutoOS.App.Sound\AutoOS.Sound.exe')">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Content Include="$(NuGetPackageRoot)leveldbsharp\$(LevelDBSharpPackageVersion)\runtimes\win-x64\native\leveldb.dll" Condition="'$(Platform)' == 'x64'">
      <Link>runtimes\win-x64\native\leveldb.dll</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="$(NuGetPackageRoot)leveldbsharp\$(LevelDBSharpPackageVersion)\runtimes\win-arm64\native\leveldb.dll" Condition="'$(Platform)' == 'ARM64'">
      <Link>runtimes\win-arm64\native\leveldb.dll</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="$(NuGetPackageRoot)leveldbsharp\$(LevelDBSharpPackageVersion)\runtimes\win-x86\native\leveldb.dll" Condition="'$(Platform)' == 'x86'">
      <Link>runtimes\win-x86\native\leveldb.dll</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <Target Name="GetVersion">
    <Message Importance="High" Text="$(Version)" />
  </Target>
</Project>
