[enabled_services]
AMD External Events Utility
AnyDesk # AnyDesk
Appinfo
AppXSvc
AudioEndpointBuilder
Audiosrv
BFE # Auto Updates / Firewall
BrokerInfrastructure
camsvc
CaptureService # Snipping Tool
cbdhsvc # Snipping Tool
COD.Broker.Service # Warzone / Blacks Ops 7
CoreMessagingRegistrar
ClipSvc # Auto Updates
CloudflareWARP # Cloudflare WARP
CryptSvc
DcomLaunch
DeviceInstall # New devices
Dhcp
DispBrokerDesktopSvc # Remember Main Monitor
Dnscache
DoSvc # Auto Updates
EABackgroundService # EA
EasyAntiCheat_EOS
gpsvc
InstallService # Auto Updates
KeyIso # Apex Legends, Pin
LicenseManager # Movies & TV
LSM
lfsvc # Location Service
mpssvc # Auto Updates / Firewall
msiserver # Auto Updates
netprofm
NgcCtnrSvc # Pin
NgcSvc # Pin
nsi
NVDisplay.ContainerLocalSystem
Power
ProfSvc
RpcEptMapper
RpcSs
seclogon
SstpSvc # Lock screen
StateRepository
Steam Client Service
sppsvc
SystemEventsBroker
SysMain
TextInputManagementService
TrustedInstaller
UdkUserSvc
UserManager
vgc # Valorant
Windhawk
Winmgmt
WpnService # Notifications
WpnUserService # Notifications
W32Time

# WiFi
# WlanSvc
# Netman
# NetSetupSvc
# NlaSvc
# Wcmsvc
# WinHttpAutoProxySvc 

# Bluetooth
# BluetoothUserService
# BTAGService
# BthAvctpSvc
# bthserv
# DeviceAssociationService
# DevicesFlowUserSvc
# DsmSvc
# NcbService
# WFDSConMgrSvc

[individual_disabled_services]
acpipagr
afunix
amdgpio2
applockerfltr
AsyncMac
bam
Beep
bfs
blbdrive
bowser
cdrom
CimFS
CldFlt
CLFS
clreg
CompositeBus
CSC
DfsC
discache
EhStorClass
fvevol
GPIOClx0101
GpuEnergyDrv
IntelPMT
iorate
kdnic
KSecPkg
ksthunk
lltdio
luafv
MRxDav
mrxsmb
mrxsmb10
mrxsmb20
MsLldp
MsSecCore
MsSecFlt
MSTEE
MSKSSRV
NdisCap
NdisVirtualBus
NdisWan
Ndu
NetBIOS
NetBT
npsvctrig
PEAUTH
PptpMiniport
PRM
P9Rdr
RasAgileVpn
Rasl2tp
RasPppoe
RasSstp
rdbss
rdpbus
RDPCDD
RDPDR
RDPENCDD
RDPREFMP
rdyboost
rspndr
secdrv
SgrmAgent
spaceport
srv
srv2
srvnet
storflt
storqosflt
tcpipreg
Telemetry
tunnel
UEFI
umbus
UnionFS
vdrvroot
volmgrx
volsnap
Vid
wanarp
Wanarpv6
wcifs
WdNisDrv
WindowsTrustedRT
WindowsTrustedRTProxy
WmiAcpi
wtd

# WiFi
tdx
vwififlt
Netwtw10
Netwtw14

# Bluetooth
BthA2dp
BthEnum
BthHFAud
BthHFEnum
BthLEEnum
BthMini
BTHMODEM
BthPan
BTHPORT
BTHUSB
HidBth
ibtusb
Microsoft_Bluetooth_AvrcpTransport
RFCOMM

[rename_binaries]
\Windows\System32\upfc.exe
\Windows\System32\backgroundTaskHost.exe