<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<RootNamespace>AutoOS.Core</RootNamespace>
		<AssemblyName>AutoOS.Core</AssemblyName>
    <TargetFramework>$(WindowsTargetFramework)</TargetFramework>
    <TargetPlatformMinVersion>$(MinimalWindowsVersion)</TargetPlatformMinVersion>

    <Platforms>x86;x64;ARM64</Platforms>
    <RuntimeIdentifiers>win-x86;win-x64;win-arm64</RuntimeIdentifiers>

    <Nullable>enable</Nullable>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="DevWinUI" />
		<PackageReference Include="Downloader" />
		<PackageReference Include="Microsoft.Data.Sqlite" />
		<PackageReference Include="Microsoft.Windows.CsWin32" />
		<PackageReference Include="Newtonsoft.Json" />
		<PackageReference Include="PhantomClient" />
		<PackageReference Include="Sep" />
		<PackageReference Include="Snappier" />
		<PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" />
		<PackageReference Include="System.ServiceProcess.ServiceController" />
		<PackageReference Include="LevelDBSharp" />
		<PackageReference Include="ValveKeyValue" />
	</ItemGroup>

	<ItemGroup>
		<Content Include="Drivers\InpOut\inpoutx64.dll">
			<Link>inpoutx64.dll</Link>
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Drivers\InpOut\inpoutx64.sys">
			<Link>inpoutx64.sys</Link>
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
	</ItemGroup>
</Project>
